# Copyright 2020 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Run functional regression checks
name: ci
on: [push, pull_request]

jobs:

  ########
  # Docs #
  ########
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: pip
    - name: Install Python dependencies
      run: pip install -r docs/requirements.txt
    - name: Build docs
      run: mkdocs build

  ################################
  # SW on Default Snitch Cluster #
  ################################
  sw-snitch-cluster-default:
    container:
      image: ghcr.io/pulp-platform/snitch
    name: SW on Default Snitch Cluster Config
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        toolchain:
        - gcc
        - llvm
        cmake_args:
        - ''
        - -DOMPSTATIC_NUMTHREADS=8
    steps:
    - uses: actions/checkout@v2
    - name: Build Hardware
      run: |
        cd hw/system/snitch_cluster && make bin/snitch_cluster.vlt
    - name: Build Software
      run: |
        cd hw/system/snitch_cluster/sw && mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=toolchain-${{ matrix.toolchain }} -DBUILD_TESTS=ON .. && make
    - name: Run Unit Tests
      run: |
        cd hw/system/snitch_cluster/sw/build && make test
